# Full encoding

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('diamonds (cleaned).csv')

In [3]:
df.head(3)

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,Cushion Modified,Ideal,F,VVS2,1.84,1.02,65.8,59.0,Excellent,Very Good,Medium to Thick,NaN,7.09,6.95,4.57,2640,GIA Lab-Grown,NaN
1,Pear,NaN,E,VS1,1.20,1.65,62.5,58.0,Very Good,Very Good,Medium to Thick,NaN,9.64,5.86,3.66,1070,GIA Lab-Grown,NaN
2,Oval,NaN,E,VS1,1.19,1.41,63.1,63.0,Very Good,Very Good,Medium to Thick,NaN,8.44,6.00,3.79,1070,GIA Lab-Grown,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6485 entries, 0 to 6484
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Shape               6480 non-null   object
 1   Cut                 2182 non-null   object
 2   Color               6480 non-null   object
 3   Clarity             6480 non-null   object
 4   Carat Weight        6480 non-null   float64
 5   Length/Width Ratio  6480 non-null   float64
 6   Depth %             6478 non-null   float64
 7   Table %             6468 non-null   float64
 8   Polish              6465 non-null   object
 9   Symmetry            6465 non-null   object
 10  Girdle              6463 non-null   object
 11  Culet               1891 non-null   object
 12  Length              6465 non-null   float64
 13  Width               6465 non-null   float64
 14  Height              6465 non-null   float64
 15  Price               6485 non-null   int64
 16  Type                6485 non-null   object
 17  Fluorescence        1221 non-null   object
dtypes: float64(7), int64(1), object(10)
memory usage: 912.1+ KB

In [5]:
df.isnull().sum()

Shape                    5
Cut                   4303
Color                    5
Clarity                  5
Carat Weight             5
Length/Width Ratio       5
Depth %                  7
Table %                 17
Polish                  20
Symmetry                20
Girdle                  22
Culet                 4594
Length                  20
Width                   20
Height                  20
Price                    0
Type                     0
Fluorescence          5264
dtype: int64

In [6]:
# faqat null qiymatlari bor ustunlarni barchasini ekranga chiqarish

missing_columns=df.isnull().sum()
missing_columns=missing_columns[missing_columns>0]
if not missing_columns.empty:
    print(f"Tushib qolgan qiymatlari bor barcha ustunlar:\n{missing_columns}")
else:
    print("Tushib qolgan qiymatlari bor ustunlar mavjud emas")

Tushib qolgan qiymatlari bor barcha ustunlar:
Shape                    5
Cut                   4303
Color                    5
Clarity                  5
Carat Weight             5
Length/Width Ratio       5
Depth %                  7
Table %                 17
Polish                  20
Symmetry                20
Girdle                  22
Culet                 4594
Length                  20
Width                   20
Height                  20
Fluorescence          5264
dtype: int64

In [28]:
# Null qiymati bor ustunlarni butunlay tashlab yuborish codi

df.dropna(axis=1,inplace=True)

In [29]:
df.head(3)

   Price           Type
0   2640  GIA Lab-Grown
1   1070  GIA Lab-Grown
2   1070  GIA Lab-Grown

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6485 entries, 0 to 6484
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   6485 non-null   int64
 1   Type    6485 non-null   object
dtypes: int64(1), object(1)
memory usage: 101.5+ KB

In [5]:
# Null qiymatlari bor qatorlarni butunlay tashlab yuborish codi

df.dropna(inplace=True)

In [6]:
df.head(3)

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
5075,Round,Very Good,H,VS2,1.00,1.01,60.3,63.0,Excellent,Very Good,Slightly Thick to Thick,Very Small,6.31,6.39,3.83,3480,GIA,Strong
5570,Round,Excellent,G,VS2,1.01,1.01,62.5,57.0,Very Good,Very Good,Medium to Slightly Thick,Very Small,6.33,6.40,3.98,4060,GIA,Faint
5907,Round,Very Good,H,VS1,1.00,1.01,64.2,60.0,Very Good,Very Good,Slightly Thick to Thick,Very Small,6.20,6.27,4.00,3480,GIA,Faint

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 5075 to 5907
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Shape               3 non-null      object
 1   Cut                 3 non-null      object
 2   Color               3 non-null      object
 3   Clarity             3 non-null      object
 4   Carat Weight        3 non-null      float64
 5   Length/Width Ratio  3 non-null      float64
 6   Depth %             3 non-null      float64
 7   Table %             3 non-null      float64
 8   Polish              3 non-null      object
 9   Symmetry            3 non-null      object
 10  Girdle              3 non-null      object
 11  Culet               3 non-null      object
 12  Length              3 non-null      float64
 13  Width               3 non-null      float64
 14  Height              3 non-null      float64
 15  Price               3 non-null      int64
 16  Type                3 non-null      object
 17  Fluorescence        3 non-null      object
dtypes: float64(7), int64(1), object(10)
memory usage: 456.0+ bytes

In [4]:
missing_columns=df.isnull().sum()
missing_columns=missing_columns[missing_columns>0]
if not missing_columns.empty:
    print(f"Tushib qolgan qiymatlari bor barcha ustunlar:\n{missing_columns}")
else:
    print("Tushib qolgan qiymatlari bor ustunlar mavjud emas")

Tushib qolgan qiymatlari bor barcha ustunlar:
Shape                    5
Cut                   4303
Color                    5
Clarity                  5
Carat Weight             5
Length/Width Ratio       5
Depth %                  7
Table %                 17
Polish                  20
Symmetry                20
Girdle                  22
Culet                 4594
Length                  20
Width                   20
Height                  20
Fluorescence          5264
dtype: int64

In [7]:
# Null qiymatlari bor ustunlarni to'ldirish umumiy codi

missing_col=df.columns[df.isnull().sum()>0]

for col in missing_col:
    if df[col].dtype=="object":
        df[col].fillna(df[col].mode()[0],inplace=True)
    else:
        df[col].fillna(df[col].mean(),inplace=True)

/var/folders/kx/n6bh82zd3w5_blhwkxh6d2440000gn/T/ipykernel_6416/3258242528.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)
/var/folders/kx/n6bh82zd3w5_blhwkxh6d2440000gn/T/ipykernel_6416/3258242528.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(),inplace=True)

In [6]:
df.head()

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,Cushion Modified,Ideal,F,VVS2,1.84,1.02,65.8,59.0,Excellent,Very Good,Medium to Thick,Pointed,7.09,6.95,4.57,2640,GIA Lab-Grown,Faint
1,Pear,Ideal,E,VS1,1.20,1.65,62.5,58.0,Very Good,Very Good,Medium to Thick,Pointed,9.64,5.86,3.66,1070,GIA Lab-Grown,Faint
2,Oval,Ideal,E,VS1,1.19,1.41,63.1,63.0,Very Good,Very Good,Medium to Thick,Pointed,8.44,6.00,3.79,1070,GIA Lab-Grown,Faint
3,Heart,Ideal,D,IF,1.00,1.18,61.7,58.0,Excellent,Excellent,Slightly Thick to Very Thick,Pointed,5.85,6.89,4.25,7110,GIA,Faint
4,Radiant,Ideal,H,VS1,1.01,1.35,69.4,66.0,Excellent,Very Good,Thick,Pointed,6.80,5.05,3.50,3050,GIA,Faint

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6485 entries, 0 to 6484
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Shape               6485 non-null   object
 1   Cut                 6485 non-null   object
 2   Color               6485 non-null   object
 3   Clarity             6485 non-null   object
 4   Carat Weight        6485 non-null   float64
 5   Length/Width Ratio  6485 non-null   float64
 6   Depth %             6485 non-null   float64
 7   Table %             6485 non-null   float64
 8   Polish              6485 non-null   object
 9   Symmetry            6485 non-null   object
 10  Girdle              6485 non-null   object
 11  Culet               6485 non-null   object
 12  Length              6485 non-null   float64
 13  Width               6485 non-null   float64
 14  Height              6485 non-null   float64
 15  Price               6485 non-null   int64
 16  Type                6485 non-null   object
 17  Fluorescence        6485 non-null   object
dtypes: float64(7), int64(1), object(10)
memory usage: 912.1+ KB

In [12]:
missing_columns=df.isnull().sum()
missing_columns=missing_columns[missing_columns>0]
if not missing_columns.empty:
    print(f"Tushib qolgan qiymatlari bor barcha ustunlar:\n{missing_columns}")
else:
    print("Tushib qolgan qiymatlari bor ustunlar mavjud emas")

Tushib qolgan qiymatlari bor ustunlar mavjud emas

In [5]:
# Categorical qiymatli ustunlarni ekranga chiqarish
categorical_col=df.select_dtypes(include=["object","category"]).columns.tolist()
categorical_col

['Shape',
 'Cut',
 'Color',
 'Clarity',
 'Polish',
 'Symmetry',
 'Girdle',
 'Culet',
 'Type',
 'Fluorescence']

In [20]:
# Encoding One-hot encoding
# get_dummies

one_hot_encoder=pd.get_dummies(df,columns=categorical_col,drop_first=True)
one_hot_encoder

,Carat Weight,Length/Width Ratio,Depth %,Table %,Length,Width,Height,Price,Shape_Cushion Modified,Shape_Emerald,...,Girdle_Very Thin to Thick,Girdle_Very Thin to Very Thick,Culet_Pointed,Culet_Small,Culet_Very Large,Culet_Very Small,Type_GIA Lab-Grown,Type_IGI Lab-Grown,Fluorescence_Medium,Fluorescence_Strong
0,1.84,1.02,65.8,59.0,7.09,6.95,4.57,2640,True,False,...,False,False,True,False,False,False,True,False,False,False
1,1.20,1.65,62.5,58.0,9.64,5.86,3.66,1070,False,False,...,False,False,True,False,False,False,True,False,False,False
2,1.19,1.41,63.1,63.0,8.44,6.00,3.79,1070,False,False,...,False,False,True,False,False,False,True,False,False,False
3,1.00,1.18,61.7,58.0,5.85,6.89,4.25,7110,False,False,...,False,False,True,False,False,False,False,False,False,False
4,1.01,1.35,69.4,66.0,6.80,5.05,3.50,3050,False,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6480,1.02,1.54,62.9,63.0,8.60,5.59,3.51,3760,False,False,...,False,False,True,False,False,False,False,False,True,False
6481,1.00,1.16,58.3,59.0,6.05,6.99,4.07,4710,False,False,...,False,False,True,False,False,False,False,False,False,True
6482,1.03,1.01,72.6,71.0,5.59,5.51,4.00,3270,False,False,...,False,False,True,False,False,False,False,False,False,False
6483,1.06,1.43,67.8,62.0,7.24,5.05,3.42,1050,False,False,...,False,False,True,False,False,False,True,False,False,False
6484,1.00,1.36,68.4,66.0,6.51,4.77,3.26,2870,False,True,...,False,False,True,False,False,False,False,False,False,False

In [22]:
one_hot_encoder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6485 entries, 0 to 6484
Data columns (total 70 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Carat Weight                              6485 non-null   float64
 1   Length/Width Ratio                        6485 non-null   float64
 2   Depth %                                   6485 non-null   float64
 3   Table %                                   6485 non-null   float64
 4   Length                                    6485 non-null   float64
 5   Width                                     6485 non-null   float64
 6   Height                                    6485 non-null   float64
 7   Price                                     6485 non-null   int64
 8   Shape_Cushion Modified                    6485 non-null   bool
 9   Shape_Emerald                             6485 non-null   bool
 10  Shape_Heart                               6485 non-null   bool
 11  Shape_Marquise                            6485 non-null   bool
 12  Shape_Oval                                6485 non-null   bool
 13  Shape_Pear                                6485 non-null   bool
 14  Shape_Princess                            6485 non-null   bool
 15  Shape_Radiant                             6485 non-null   bool
 16  Shape_Round                               6485 non-null   bool
 17  Shape_Square Radiant                      6485 non-null   bool
 18  Cut_Excellent                             6485 non-null   bool
 19  Cut_Ideal                                 6485 non-null   bool
 20  Cut_Very Good                             6485 non-null   bool
 21  Color_E                                   6485 non-null   bool
 22  Color_F                                   6485 non-null   bool
 23  Color_G                                   6485 non-null   bool
 24  Color_H                                   6485 non-null   bool
 25  Clarity_IF                                6485 non-null   bool
 26  Clarity_VS1                               6485 non-null   bool
 27  Clarity_VS2                               6485 non-null   bool
 28  Clarity_VVS1                              6485 non-null   bool
 29  Clarity_VVS2                              6485 non-null   bool
 30  Polish_Good                               6485 non-null   bool
 31  Polish_Very Good                          6485 non-null   bool
 32  Symmetry_Good                             6485 non-null   bool
 33  Symmetry_Very Good                        6485 non-null   bool
 34  Girdle_Extremely Thin to Extremely Thick  6485 non-null   bool
 35  Girdle_Extremely Thin to Medium           6485 non-null   bool
 36  Girdle_Extremely Thin to Slightly Thick   6485 non-null   bool
 37  Girdle_Medium                             6485 non-null   bool
 38  Girdle_Medium to Extremely Thick          6485 non-null   bool
 39  Girdle_Medium to Slightly Thick           6485 non-null   bool
 40  Girdle_Medium to Thick                    6485 non-null   bool
 41  Girdle_Medium to Very Thick               6485 non-null   bool
 42  Girdle_Slightly Thick                     6485 non-null   bool
 43  Girdle_Slightly Thick to Extremely Thick  6485 non-null   bool
 44  Girdle_Slightly Thick to Slightly Thick   6485 non-null   bool
 45  Girdle_Slightly Thick to Thick            6485 non-null   bool
 46  Girdle_Slightly Thick to Very Thick       6485 non-null   bool
 47  Girdle_Thick                              6485 non-null   bool
 48  Girdle_Thick to Extremely Thick           6485 non-null   bool
 49  Girdle_Thick to Very Thick                6485 non-null   bool
 50  Girdle_Thin                               6485 non-null   bool
 51  Girdle_Thin to Extremely Thick            6485 non-null   bool
 52  Girdle_Thin to Medium                     6485 non-null   bool
 53  Girdle_Thin to Slightly Thick             6485 non-null   bool
 54  Girdle_Thin to Thick                      6485 non-null   bool
 55  Girdle_Thin to Very Thick                 6485 non-null   bool
 56  Girdle_Very Thick                         6485 non-null   bool
 57  Girdle_Very Thick to Extremely Thick      6485 non-null   bool
 58  Girdle_Very Thin to Extremely Thick       6485 non-null   bool
 59  Girdle_Very Thin to Slightly Thick        6485 non-null   bool
 60  Girdle_Very Thin to Thick                 6485 non-null   bool
 61  Girdle_Very Thin to Very Thick            6485 non-null   bool
 62  Culet_Pointed                             6485 non-null   bool
 63  Culet_Small                               6485 non-null   bool
 64  Culet_Very Large                          6485 non-null   bool
 65  Culet_Very Small                          6485 non-null   bool
 66  Type_GIA Lab-Grown                        6485 non-null   bool
 67  Type_IGI Lab-Grown                        6485 non-null   bool
 68  Fluorescence_Medium                       6485 non-null   bool
 69  Fluorescence_Strong                       6485 non-null   bool
dtypes: bool(62), float64(7), int64(1)
memory usage: 798.1 KB

In [24]:
df.one_hot=one_hot_encoder

/var/folders/kx/n6bh82zd3w5_blhwkxh6d2440000gn/T/ipykernel_4419/2013703063.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.one_hot=one_hot_encoder

In [29]:
df=df.one_hot.astype(int)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6485 entries, 0 to 6484
Data columns (total 70 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Carat Weight                              6485 non-null   int64
 1   Length/Width Ratio                        6485 non-null   int64
 2   Depth %                                   6485 non-null   int64
 3   Table %                                   6485 non-null   int64
 4   Length                                    6485 non-null   int64
 5   Width                                     6485 non-null   int64
 6   Height                                    6485 non-null   int64
 7   Price                                     6485 non-null   int64
 8   Shape_Cushion Modified                    6485 non-null   int64
 9   Shape_Emerald                             6485 non-null   int64
 10  Shape_Heart                               6485 non-null   int64
 11  Shape_Marquise                            6485 non-null   int64
 12  Shape_Oval                                6485 non-null   int64
 13  Shape_Pear                                6485 non-null   int64
 14  Shape_Princess                            6485 non-null   int64
 15  Shape_Radiant                             6485 non-null   int64
 16  Shape_Round                               6485 non-null   int64
 17  Shape_Square Radiant                      6485 non-null   int64
 18  Cut_Excellent                             6485 non-null   int64
 19  Cut_Ideal                                 6485 non-null   int64
 20  Cut_Very Good                             6485 non-null   int64
 21  Color_E                                   6485 non-null   int64
 22  Color_F                                   6485 non-null   int64
 23  Color_G                                   6485 non-null   int64
 24  Color_H                                   6485 non-null   int64
 25  Clarity_IF                                6485 non-null   int64
 26  Clarity_VS1                               6485 non-null   int64
 27  Clarity_VS2                               6485 non-null   int64
 28  Clarity_VVS1                              6485 non-null   int64
 29  Clarity_VVS2                              6485 non-null   int64
 30  Polish_Good                               6485 non-null   int64
 31  Polish_Very Good                          6485 non-null   int64
 32  Symmetry_Good                             6485 non-null   int64
 33  Symmetry_Very Good                        6485 non-null   int64
 34  Girdle_Extremely Thin to Extremely Thick  6485 non-null   int64
 35  Girdle_Extremely Thin to Medium           6485 non-null   int64
 36  Girdle_Extremely Thin to Slightly Thick   6485 non-null   int64
 37  Girdle_Medium                             6485 non-null   int64
 38  Girdle_Medium to Extremely Thick          6485 non-null   int64
 39  Girdle_Medium to Slightly Thick           6485 non-null   int64
 40  Girdle_Medium to Thick                    6485 non-null   int64
 41  Girdle_Medium to Very Thick               6485 non-null   int64
 42  Girdle_Slightly Thick                     6485 non-null   int64
 43  Girdle_Slightly Thick to Extremely Thick  6485 non-null   int64
 44  Girdle_Slightly Thick to Slightly Thick   6485 non-null   int64
 45  Girdle_Slightly Thick to Thick            6485 non-null   int64
 46  Girdle_Slightly Thick to Very Thick       6485 non-null   int64
 47  Girdle_Thick                              6485 non-null   int64
 48  Girdle_Thick to Extremely Thick           6485 non-null   int64
 49  Girdle_Thick to Very Thick                6485 non-null   int64
 50  Girdle_Thin                               6485 non-null   int64
 51  Girdle_Thin to Extremely Thick            6485 non-null   int64
 52  Girdle_Thin to Medium                     6485 non-null   int64
 53  Girdle_Thin to Slightly Thick             6485 non-null   int64
 54  Girdle_Thin to Thick                      6485 non-null   int64
 55  Girdle_Thin to Very Thick                 6485 non-null   int64
 56  Girdle_Very Thick                         6485 non-null   int64
 57  Girdle_Very Thick to Extremely Thick      6485 non-null   int64
 58  Girdle_Very Thin to Extremely Thick       6485 non-null   int64
 59  Girdle_Very Thin to Slightly Thick        6485 non-null   int64
 60  Girdle_Very Thin to Thick                 6485 non-null   int64
 61  Girdle_Very Thin to Very Thick            6485 non-null   int64
 62  Culet_Pointed                             6485 non-null   int64
 63  Culet_Small                               6485 non-null   int64
 64  Culet_Very Large                          6485 non-null   int64
 65  Culet_Very Small                          6485 non-null   int64
 66  Type_GIA Lab-Grown                        6485 non-null   int64
 67  Type_IGI Lab-Grown                        6485 non-null   int64
 68  Fluorescence_Medium                       6485 non-null   int64
 69  Fluorescence_Strong                       6485 non-null   int64
dtypes: int64(70)
memory usage: 3.5 MB

In [8]:
# OneHotEncoder

from sklearn.preprocessing import OneHotEncoder,LabelEncoder # kutubxonani chaqirish

In [9]:
# Categorical qiymatli ustunlarni ekranga chiqarish
categorical_col=df.select_dtypes(include=["object","category"]).columns.tolist()
categorical_col

['Shape',
 'Cut',
 'Color',
 'Clarity',
 'Polish',
 'Symmetry',
 'Girdle',
 'Culet',
 'Type',
 'Fluorescence']

In [13]:
one_hot=OneHotEncoder(sparse_output=False,drop="first")# one_hot deb o'zgaruvchini belgilab oldik
df_encoded=one_hot.fit_transform(df[categorical_col]) # numericalga o'tish9transform qilish

In [14]:
df_encoded

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(6485, 62))

In [12]:
df_encoded_col=one_hot.get_feature_names_out(categorical_col)# ochilgan yanghi ustunlarga nom berish amali
df_encoded_col

array(['Shape_Cushion Modified', 'Shape_Emerald', 'Shape_Heart',
       'Shape_Marquise', 'Shape_Oval', 'Shape_Pear', 'Shape_Princess',
       'Shape_Radiant', 'Shape_Round', 'Shape_Square Radiant',
       'Cut_Excellent', 'Cut_Ideal', 'Cut_Very Good', 'Color_E',
       'Color_F', 'Color_G', 'Color_H', 'Clarity_IF', 'Clarity_VS1',
       'Clarity_VS2', 'Clarity_VVS1', 'Clarity_VVS2', 'Polish_Good',
       'Polish_Very Good', 'Symmetry_Good', 'Symmetry_Very Good',
       'Girdle_Extremely Thin to Extremely Thick',
       'Girdle_Extremely Thin to Medium',
       'Girdle_Extremely Thin to Slightly Thick', 'Girdle_Medium',
       'Girdle_Medium to Extremely Thick',
       'Girdle_Medium to Slightly Thick', 'Girdle_Medium to Thick',
       'Girdle_Medium to Very Thick', 'Girdle_Slightly Thick',
       'Girdle_Slightly Thick to Extremely Thick',
       'Girdle_Slightly Thick to Slightly Thick',
       'Girdle_Slightly Thick to Thick',
       'Girdle_Slightly Thick to Very Thick', 'Girdle_Thick',
       'Girdle_Thick to Extremely Thick', 'Girdle_Thick to Very Thick',
       'Girdle_Thin', 'Girdle_Thin to Extremely Thick',
       'Girdle_Thin to Medium', 'Girdle_Thin to Slightly Thick',
       'Girdle_Thin to Thick', 'Girdle_Thin to Very Thick',
       'Girdle_Very Thick', 'Girdle_Very Thick to Extremely Thick',
       'Girdle_Very Thin to Extremely Thick',
       'Girdle_Very Thin to Slightly Thick', 'Girdle_Very Thin to Thick',
       'Girdle_Very Thin to Very Thick', 'Culet_Pointed', 'Culet_Small',
       'Culet_Very Large', 'Culet_Very Small', 'Type_GIA Lab-Grown',
       'Type_IGI Lab-Grown', 'Fluorescence_Medium', 'Fluorescence_Strong'],
      dtype=object)

In [16]:
# ochilgan yangi ustunlarni bo'glash va eskilarini o'chirib yuborish

df_encoded=pd.DataFrame(df_encoded)
df_ncoded=pd.concat([df.drop(columns=categorical_col), df_encoded],axis=1)

In [17]:
df_encoded.head()

,0,1,2,3,4,5,6,7,8,9,...,52,53,54,55,56,57,58,59,60,61
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6485 entries, 0 to 6484
Data columns (total 62 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       6485 non-null   float64
 1   1       6485 non-null   float64
 2   2       6485 non-null   float64
 3   3       6485 non-null   float64
 4   4       6485 non-null   float64
 5   5       6485 non-null   float64
 6   6       6485 non-null   float64
 7   7       6485 non-null   float64
 8   8       6485 non-null   float64
 9   9       6485 non-null   float64
 10  10      6485 non-null   float64
 11  11      6485 non-null   float64
 12  12      6485 non-null   float64
 13  13      6485 non-null   float64
 14  14      6485 non-null   float64
 15  15      6485 non-null   float64
 16  16      6485 non-null   float64
 17  17      6485 non-null   float64
 18  18      6485 non-null   float64
 19  19      6485 non-null   float64
 20  20      6485 non-null   float64
 21  21      6485 non-null   float64
 22  22      6485 non-null   float64
 23  23      6485 non-null   float64
 24  24      6485 non-null   float64
 25  25      6485 non-null   float64
 26  26      6485 non-null   float64
 27  27      6485 non-null   float64
 28  28      6485 non-null   float64
 29  29      6485 non-null   float64
 30  30      6485 non-null   float64
 31  31      6485 non-null   float64
 32  32      6485 non-null   float64
 33  33      6485 non-null   float64
 34  34      6485 non-null   float64
 35  35      6485 non-null   float64
 36  36      6485 non-null   float64
 37  37      6485 non-null   float64
 38  38      6485 non-null   float64
 39  39      6485 non-null   float64
 40  40      6485 non-null   float64
 41  41      6485 non-null   float64
 42  42      6485 non-null   float64
 43  43      6485 non-null   float64
 44  44      6485 non-null   float64
 45  45      6485 non-null   float64
 46  46      6485 non-null   float64
 47  47      6485 non-null   float64
 48  48      6485 non-null   float64
 49  49      6485 non-null   float64
 50  50      6485 non-null   float64
 51  51      6485 non-null   float64
 52  52      6485 non-null   float64
 53  53      6485 non-null   float64
 54  54      6485 non-null   float64
 55  55      6485 non-null   float64
 56  56      6485 non-null   float64
 57  57      6485 non-null   float64
 58  58      6485 non-null   float64
 59  59      6485 non-null   float64
 60  60      6485 non-null   float64
 61  61      6485 non-null   float64
dtypes: float64(62)
memory usage: 3.1 MB

In [8]:
# Categorical qiymatli ustunlarni ekranga chiqarish
categorical_col=df.select_dtypes(include=["object","category"]).columns.tolist()
categorical_col

['Shape',
 'Cut',
 'Color',
 'Clarity',
 'Polish',
 'Symmetry',
 'Girdle',
 'Culet',
 'Type',
 'Fluorescence']

In [6]:
# Label encoding

from sklearn.preprocessing import LabelEncoder # kutubxonani chaqirish

In [12]:
encoder=LabelEncoder()
df[categorical_col]=df[categorical_col].apply(encoder.fit_transform)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6485 entries, 0 to 6484
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Shape               6485 non-null   int64
 1   Cut                 6485 non-null   int64
 2   Color               6485 non-null   int64
 3   Clarity             6485 non-null   int64
 4   Carat Weight        6485 non-null   float64
 5   Length/Width Ratio  6485 non-null   float64
 6   Depth %             6485 non-null   float64
 7   Table %             6485 non-null   float64
 8   Polish              6485 non-null   int64
 9   Symmetry            6485 non-null   int64
 10  Girdle              6485 non-null   int64
 11  Culet               6485 non-null   int64
 12  Length              6485 non-null   float64
 13  Width               6485 non-null   float64
 14  Height              6485 non-null   float64
 15  Price               6485 non-null   int64
 16  Type                6485 non-null   int64
 17  Fluorescence        6485 non-null   int64
dtypes: float64(7), int64(11)
memory usage: 912.1 KB

In [14]:
df.head()

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,1,2,2,5,1.84,1.02,65.8,59.0,0,2,7,1,7.09,6.95,4.57,2640,1,0
1,6,2,1,2,1.20,1.65,62.5,58.0,2,2,7,1,9.64,5.86,3.66,1070,1,0
2,5,2,1,2,1.19,1.41,63.1,63.0,2,2,7,1,8.44,6.00,3.79,1070,1,0
3,3,2,0,1,1.00,1.18,61.7,58.0,0,0,13,1,5.85,6.89,4.25,7110,0,0
4,8,2,4,2,1.01,1.35,69.4,66.0,0,2,14,1,6.80,5.05,3.50,3050,0,0

In [7]:
# Categorical qiymatli ustunlarni ekranga chiqarish
categorical_col=df.select_dtypes(include=["object","category"]).columns.tolist()
categorical_col

['Shape',
 'Cut',
 'Color',
 'Clarity',
 'Polish',
 'Symmetry',
 'Girdle',
 'Culet',
 'Type',
 'Fluorescence']

In [8]:
# label encoding for loop bilan
label_encoder=LabelEncoder()
for col in categorical_col:
    df[col]=label_encoder.fit_transform(df[col])

In [9]:
df.head()

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,1,2,2,5,1.84,1.02,65.8,59.0,0,2,7,1,7.09,6.95,4.57,2640,1,0
1,6,2,1,2,1.20,1.65,62.5,58.0,2,2,7,1,9.64,5.86,3.66,1070,1,0
2,5,2,1,2,1.19,1.41,63.1,63.0,2,2,7,1,8.44,6.00,3.79,1070,1,0
3,3,2,0,1,1.00,1.18,61.7,58.0,0,0,13,1,5.85,6.89,4.25,7110,0,0
4,8,2,4,2,1.01,1.35,69.4,66.0,0,2,14,1,6.80,5.05,3.50,3050,0,0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6485 entries, 0 to 6484
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Shape               6485 non-null   int64
 1   Cut                 6485 non-null   int64
 2   Color               6485 non-null   int64
 3   Clarity             6485 non-null   int64
 4   Carat Weight        6485 non-null   float64
 5   Length/Width Ratio  6485 non-null   float64
 6   Depth %             6485 non-null   float64
 7   Table %             6485 non-null   float64
 8   Polish              6485 non-null   int64
 9   Symmetry            6485 non-null   int64
 10  Girdle              6485 non-null   int64
 11  Culet               6485 non-null   int64
 12  Length              6485 non-null   float64
 13  Width               6485 non-null   float64
 14  Height              6485 non-null   float64
 15  Price               6485 non-null   int64
 16  Type                6485 non-null   int64
 17  Fluorescence        6485 non-null   int64
dtypes: float64(7), int64(11)
memory usage: 912.1 KB

# Frequency va Target (mean) encoding

In [6]:
df.head(3)

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,Cushion Modified,Ideal,F,VVS2,1.84,1.02,65.8,59.0,Excellent,Very Good,Medium to Thick,Pointed,7.09,6.95,4.57,2640,GIA Lab-Grown,Faint
1,Pear,Ideal,E,VS1,1.20,1.65,62.5,58.0,Very Good,Very Good,Medium to Thick,Pointed,9.64,5.86,3.66,1070,GIA Lab-Grown,Faint
2,Oval,Ideal,E,VS1,1.19,1.41,63.1,63.0,Very Good,Very Good,Medium to Thick,Pointed,8.44,6.00,3.79,1070,GIA Lab-Grown,Faint

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6485 entries, 0 to 6484
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Shape               6485 non-null   object
 1   Cut                 6485 non-null   object
 2   Color               6485 non-null   object
 3   Clarity             6485 non-null   object
 4   Carat Weight        6485 non-null   float64
 5   Length/Width Ratio  6485 non-null   float64
 6   Depth %             6485 non-null   float64
 7   Table %             6485 non-null   float64
 8   Polish              6485 non-null   object
 9   Symmetry            6485 non-null   object
 10  Girdle              6485 non-null   object
 11  Culet               6485 non-null   object
 12  Length              6485 non-null   float64
 13  Width               6485 non-null   float64
 14  Height              6485 non-null   float64
 15  Price               6485 non-null   int64
 16  Type                6485 non-null   object
 17  Fluorescence        6485 non-null   object
dtypes: float64(7), int64(1), object(10)
memory usage: 912.1+ KB

In [8]:
# Categorical qiymatli ustunlarni ekranga chiqarish
categorical_col=df.select_dtypes(include=["object","category"]).columns.tolist()
categorical_col

['Shape',
 'Cut',
 'Color',
 'Clarity',
 'Polish',
 'Symmetry',
 'Girdle',
 'Culet',
 'Type',
 'Fluorescence']

In [12]:
#Frequency encoding

df[categorical_col]=df[categorical_col].apply(lambda col:col.map(col.value_counts()))

In [13]:
df.head()

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,365,5613,969,1061,1.84,1.02,65.8,59.0,5959,1790,672,6455,7.09,6.95,4.57,2640,1254,5959
1,840,5613,1889,3342,1.20,1.65,62.5,58.0,492,1790,672,6455,9.64,5.86,3.66,1070,1254,5959
2,828,5613,1889,3342,1.19,1.41,63.1,63.0,492,1790,672,6455,8.44,6.00,3.79,1070,1254,5959
3,827,5613,1772,163,1.00,1.18,61.7,58.0,5959,4571,526,6455,5.85,6.89,4.25,7110,3355,5959
4,801,5613,1117,3342,1.01,1.35,69.4,66.0,5959,1790,199,6455,6.80,5.05,3.50,3050,3355,5959

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6485 entries, 0 to 6484
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Shape               6485 non-null   int64
 1   Cut                 6485 non-null   int64
 2   Color               6485 non-null   int64
 3   Clarity             6485 non-null   int64
 4   Carat Weight        6485 non-null   float64
 5   Length/Width Ratio  6485 non-null   float64
 6   Depth %             6485 non-null   float64
 7   Table %             6485 non-null   float64
 8   Polish              6485 non-null   int64
 9   Symmetry            6485 non-null   int64
 10  Girdle              6485 non-null   int64
 11  Culet               6485 non-null   int64
 12  Length              6485 non-null   float64
 13  Width               6485 non-null   float64
 14  Height              6485 non-null   float64
 15  Price               6485 non-null   int64
 16  Type                6485 non-null   int64
 17  Fluorescence        6485 non-null   int64
dtypes: float64(7), int64(11)
memory usage: 912.1 KB

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6485 entries, 0 to 6484
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Shape               6485 non-null   object
 1   Cut                 6485 non-null   object
 2   Color               6485 non-null   object
 3   Clarity             6485 non-null   object
 4   Carat Weight        6485 non-null   float64
 5   Length/Width Ratio  6485 non-null   float64
 6   Depth %             6485 non-null   float64
 7   Table %             6485 non-null   float64
 8   Polish              6485 non-null   object
 9   Symmetry            6485 non-null   object
 10  Girdle              6485 non-null   object
 11  Culet               6485 non-null   object
 12  Length              6485 non-null   float64
 13  Width               6485 non-null   float64
 14  Height              6485 non-null   float64
 15  Price               6485 non-null   int64
 16  Type                6485 non-null   object
 17  Fluorescence        6485 non-null   object
dtypes: float64(7), int64(1), object(10)
memory usage: 912.1+ KB

In [5]:
# Categorical qiymatli ustunlarni ekranga chiqarish
categorical_col=df.select_dtypes(include=["object","category"]).columns.tolist()
categorical_col

['Shape',
 'Cut',
 'Color',
 'Clarity',
 'Polish',
 'Symmetry',
 'Girdle',
 'Culet',
 'Type',
 'Fluorescence']

In [12]:
# Target(mean) encoding

df[categorical_col]=df[categorical_col].apply(lambda col:col.map(df.groupby(col)["Price"].mean()))

In [13]:
df.head(3)

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,3891.150685,3602.046856,3531.094943,3499.887842,1.84,1.02,65.8,59.0,3399.206746,4442.1,4319.345238,3487.915259,7.09,6.95,4.57,2640,2705.92504,3447.208592
1,2773.966667,3602.046856,2781.088936,2741.618791,1.20,1.65,62.5,58.0,4765.853659,4442.1,4319.345238,3487.915259,9.64,5.86,3.66,1070,2705.92504,3447.208592
2,2857.266908,3602.046856,2781.088936,2741.618791,1.19,1.41,63.1,63.0,4765.853659,4442.1,4319.345238,3487.915259,8.44,6.00,3.79,1070,2705.92504,3447.208592

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6485 entries, 0 to 6484
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Shape               6485 non-null   float64
 1   Cut                 6485 non-null   float64
 2   Color               6485 non-null   float64
 3   Clarity             6485 non-null   float64
 4   Carat Weight        6485 non-null   float64
 5   Length/Width Ratio  6485 non-null   float64
 6   Depth %             6485 non-null   float64
 7   Table %             6485 non-null   float64
 8   Polish              6485 non-null   float64
 9   Symmetry            6485 non-null   float64
 10  Girdle              6485 non-null   float64
 11  Culet               6485 non-null   float64
 12  Length              6485 non-null   float64
 13  Width               6485 non-null   float64
 14  Height              6485 non-null   float64
 15  Price               6485 non-null   int64
 16  Type                6485 non-null   float64
 17  Fluorescence        6485 non-null   float64
dtypes: float64(17), int64(1)
memory usage: 912.1 KB

# Scaling

In [15]:

from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler, RobustScaler # kutubxonadan chaqirib olish

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6485 entries, 0 to 6484
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Shape               6485 non-null   float64
 1   Cut                 6485 non-null   float64
 2   Color               6485 non-null   float64
 3   Clarity             6485 non-null   float64
 4   Carat Weight        6485 non-null   float64
 5   Length/Width Ratio  6485 non-null   float64
 6   Depth %             6485 non-null   float64
 7   Table %             6485 non-null   float64
 8   Polish              6485 non-null   float64
 9   Symmetry            6485 non-null   float64
 10  Girdle              6485 non-null   float64
 11  Culet               6485 non-null   float64
 12  Length              6485 non-null   float64
 13  Width               6485 non-null   float64
 14  Height              6485 non-null   float64
 15  Price               6485 non-null   int64
 16  Type                6485 non-null   float64
 17  Fluorescence        6485 non-null   float64
dtypes: float64(17), int64(1)
memory usage: 912.1 KB

In [17]:
df.head()

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,3891.150685,3602.046856,3531.094943,3499.887842,1.84,1.02,65.8,59.0,3399.206746,4442.100000,4319.345238,3487.915259,7.09,6.95,4.57,2640,2705.925040,3447.208592
1,2773.966667,3602.046856,2781.088936,2741.618791,1.20,1.65,62.5,58.0,4765.853659,4442.100000,4319.345238,3487.915259,9.64,5.86,3.66,1070,2705.925040,3447.208592
2,2857.266908,3602.046856,2781.088936,2741.618791,1.19,1.41,63.1,63.0,4765.853659,4442.100000,4319.345238,3487.915259,8.44,6.00,3.79,1070,2705.925040,3447.208592
3,5216.532044,3602.046856,3715.074492,7415.950920,1.00,1.18,61.7,58.0,3399.206746,3112.168891,5370.534221,3487.915259,5.85,6.89,4.25,7110,4890.969598,3447.208592
4,2651.285893,3602.046856,3851.471799,2741.618791,1.01,1.35,69.4,66.0,3399.206746,4442.100000,3573.567839,3487.915259,6.80,5.05,3.50,3050,4890.969598,3447.208592

In [18]:
# Standard Scaling 
standard_scaler = StandardScaler()
df_standard_scaled = pd.DataFrame(standard_scaler.fit_transform(df), columns=df.columns)

In [19]:
df.head()

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,3891.150685,3602.046856,3531.094943,3499.887842,1.84,1.02,65.8,59.0,3399.206746,4442.100000,4319.345238,3487.915259,7.09,6.95,4.57,2640,2705.925040,3447.208592
1,2773.966667,3602.046856,2781.088936,2741.618791,1.20,1.65,62.5,58.0,4765.853659,4442.100000,4319.345238,3487.915259,9.64,5.86,3.66,1070,2705.925040,3447.208592
2,2857.266908,3602.046856,2781.088936,2741.618791,1.19,1.41,63.1,63.0,4765.853659,4442.100000,4319.345238,3487.915259,8.44,6.00,3.79,1070,2705.925040,3447.208592
3,5216.532044,3602.046856,3715.074492,7415.950920,1.00,1.18,61.7,58.0,3399.206746,3112.168891,5370.534221,3487.915259,5.85,6.89,4.25,7110,4890.969598,3447.208592
4,2651.285893,3602.046856,3851.471799,2741.618791,1.01,1.35,69.4,66.0,3399.206746,4442.100000,3573.567839,3487.915259,6.80,5.05,3.50,3050,4890.969598,3447.208592

In [20]:
df_standard_scaled.head(3)

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,0.290738,0.335046,0.003112,-0.027436,1.193155,-0.950828,0.334050,-0.595033,-0.255953,1.367332,0.582006,-0.061456,-0.343069,0.741048,1.143443,-0.271141,-0.565872,-0.296451
1,-0.607118,0.335046,-1.367006,-0.732580,-0.070637,0.984323,-0.357738,-0.805400,2.430977,1.367332,0.582006,-0.061456,1.182095,-0.207366,-0.377154,-0.749772,-0.565872,-0.296451
2,-0.540172,0.335046,-1.367006,-0.732580,-0.090384,0.247122,-0.231958,0.246437,2.430977,1.367332,0.582006,-0.061456,0.464371,-0.085552,-0.159926,-0.749772,-0.565872,-0.296451

In [21]:
# Min-Max Scaling
min_max_scaler = MinMaxScaler()
df_min_max_scaled = pd.DataFrame(min_max_scaler.fit_transform(df), columns=df.columns)

In [22]:
df.head()

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,3891.150685,3602.046856,3531.094943,3499.887842,1.84,1.02,65.8,59.0,3399.206746,4442.100000,4319.345238,3487.915259,7.09,6.95,4.57,2640,2705.925040,3447.208592
1,2773.966667,3602.046856,2781.088936,2741.618791,1.20,1.65,62.5,58.0,4765.853659,4442.100000,4319.345238,3487.915259,9.64,5.86,3.66,1070,2705.925040,3447.208592
2,2857.266908,3602.046856,2781.088936,2741.618791,1.19,1.41,63.1,63.0,4765.853659,4442.100000,4319.345238,3487.915259,8.44,6.00,3.79,1070,2705.925040,3447.208592
3,5216.532044,3602.046856,3715.074492,7415.950920,1.00,1.18,61.7,58.0,3399.206746,3112.168891,5370.534221,3487.915259,5.85,6.89,4.25,7110,4890.969598,3447.208592
4,2651.285893,3602.046856,3851.471799,2741.618791,1.01,1.35,69.4,66.0,3399.206746,4442.100000,3573.567839,3487.915259,6.80,5.05,3.50,3050,4890.969598,3447.208592

In [23]:
df_min_max_scaled.head()

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,0.427992,0.287846,0.434004,0.057685,0.100239,0.012658,0.637540,0.296296,0.000000,0.507247,0.268140,0.0,0.190429,0.241874,0.345455,0.042393,0.326882,0.0
1,0.105498,0.287846,0.000000,0.000000,0.023866,0.411392,0.530744,0.259259,0.270376,0.507247,0.268140,0.0,0.444666,0.137667,0.180000,0.001560,0.326882,0.0
2,0.129544,0.287846,0.000000,0.000000,0.022673,0.259494,0.550162,0.444444,0.270376,0.507247,0.268140,0.0,0.325025,0.151052,0.203636,0.001560,0.326882,0.0
3,0.810585,0.287846,0.540466,0.355596,0.000000,0.113924,0.504854,0.259259,0.000000,0.000000,0.361979,0.0,0.066800,0.236138,0.287273,0.158648,1.000000,0.0
4,0.070084,0.287846,0.619395,0.000000,0.001193,0.221519,0.754045,0.555556,0.000000,0.507247,0.201565,0.0,0.161515,0.060229,0.150909,0.053056,1.000000,0.0

In [24]:
# Robust Scaling 
robust_scaler = RobustScaler()
df_robust_scaled = pd.DataFrame(robust_scaler.fit_transform(df), columns=df.columns)

In [25]:
df.head()

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,3891.150685,3602.046856,3531.094943,3499.887842,1.84,1.02,65.8,59.0,3399.206746,4442.100000,4319.345238,3487.915259,7.09,6.95,4.57,2640,2705.925040,3447.208592
1,2773.966667,3602.046856,2781.088936,2741.618791,1.20,1.65,62.5,58.0,4765.853659,4442.100000,4319.345238,3487.915259,9.64,5.86,3.66,1070,2705.925040,3447.208592
2,2857.266908,3602.046856,2781.088936,2741.618791,1.19,1.41,63.1,63.0,4765.853659,4442.100000,4319.345238,3487.915259,8.44,6.00,3.79,1070,2705.925040,3447.208592
3,5216.532044,3602.046856,3715.074492,7415.950920,1.00,1.18,61.7,58.0,3399.206746,3112.168891,5370.534221,3487.915259,5.85,6.89,4.25,7110,4890.969598,3447.208592
4,2651.285893,3602.046856,3851.471799,2741.618791,1.01,1.35,69.4,66.0,3399.206746,4442.100000,3573.567839,3487.915259,6.80,5.05,3.50,3050,4890.969598,3447.208592

In [26]:
df_robust_scaled.head()

,Shape,Cut,Color,Clarity,Carat Weight,Length/Width Ratio,Depth %,Table %,Polish,Symmetry,Girdle,Culet,Length,Width,Height,Price,Type,Fluorescence
0,0.403035,0.0,-0.171882,0.440401,4.263158,-0.510204,0.421875,-0.285714,0.000000,1.0,0.165205,0.0,-0.142857,1.100840,1.406250,-0.213836,-0.673118,0.0
1,-0.032473,0.0,-0.872571,0.000000,0.894737,0.775510,-0.093750,-0.428571,1366.646912,1.0,0.165205,0.0,0.961039,0.184874,-0.015625,-0.707547,-0.673118,0.0
2,0.000000,0.0,-0.872571,0.000000,0.842105,0.285714,0.000000,0.285714,1366.646912,1.0,0.165205,0.0,0.441558,0.302521,0.187500,-0.707547,-0.673118,0.0
3,0.919703,0.0,0.000000,2.714842,-0.157895,-0.183673,-0.218750,-0.428571,0.000000,0.0,0.615792,0.0,-0.679654,1.050420,0.906250,1.191824,0.000000,0.0
4,-0.080297,0.0,0.127429,0.000000,-0.105263,0.163265,0.984375,0.714286,0.000000,1.0,-0.154469,0.0,-0.268398,-0.495798,-0.265625,-0.084906,0.000000,0.0